export const GET_CARDS = "GET_CARDS";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const FETCH_FAILED = "FETCH_FAILED";
export const DELETE_CARD = "DELETE_CARD";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAILED = "DELETE_CARD_FAILED";
export const DELETE_CARD_FROM = "DELETE_CARD_FROM";
export const OPEN_CARD_PANEL = "OPEN_CARD_PANEL";
export const DELETE_CARD_PANEL = "DELETE_CARD_PANEL";
export const RUN_FILTER = "RUN_FILTER";

